[package]
name = "jammy"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

poem = "3"
poem-openapi = { version = "5", features = ["swagger-ui"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

chrono = { version = "0.4", features = ["serde"] }

rand = "0.8"
lazy_static = "1"

argon2 = "0.5"
password-hash = "0.5"

hmac = "0.12"
sha2 = "0.10"
jwt = "0.16"

surrealdb = { version = "1", features = ["kv-rocksdb"] }
reqwest = { version = "0.12", default-features = false, features = ["json"] }
